### ISSUE TITLE
dokumentacja kodu

### ISSUE THREAD

**Issue by papryku** [wilczany/RezerwacjaBiletow-projekt#4]
Jest to jedna z ocenianych części projektu, musimy w jakiś sposób dokumentować kod.
Moja propozycja to javadocs, można przykładowo kogoś przydzielić do przystosowania komentarzy pod javadocs lub każdy oddzielnie by za swoje javadocs odpowiadał. Poza tym przy dziwnych fragmentach na ten moment komentarze bardzo mile widziane.

**Comment by wilczany** [comment]
Wydaje mi się ze najlepiej na bieżąco robić komentarze. Spróbujcie znaleźć narzędzie które zautomatyzuje tworzenie ich.

**Comment by papryku** [comment]
javadocs wygrał, robienie na biężąco tylko jednej osobie wychodzi xDD, zamykam
