### ISSUE TITLE
Dostepność samolotów

### ISSUE THREAD

**Issue by wilczany** [wilczany/RezerwacjaBiletow-projekt#5]
Musimy uwzględnić dostepność samolotów przy tworzeniu nowych lotów. Do uzgodnienia jest czy ma to być jedynie ze względu na datę i czas przelotu, czy również na lotnisko na ktorym znajduje sie samolot.

**Comment by papryku** [comment]
koniec końców dogadane na samą datę i czas przelotu, zamykam
